version: "3"

services:
  app:
    container_name: tutorial-app
    build:
      context: ./build/app
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/dip-dev/go-tutorial
  mock:
    container_name: mock-server
    image: dipinc/go-tutorial-mock:latest
    ports:
      - "8081:80"
